int totalVehicle;
Lock* lineLock;
List* limoQ, carQ;
List* valetQ;	
Lock* keyLock[];
Condition* keyCV[];
Lock* vehicleLock[];
Condition* vehicleCV[];
Lock* tokenLock[];
Condition* tokenCV[];
Lock* readingLock[];
Condition* readingCV[];
Lock* tipLock[];
Condition* tipCV[];
List* leavingQ;